#!/bin/bash
set -euo pipefail

source cirrus-env QA
export VERSION_WITH_BUILDNUMBER=$(npm pkg get version | tr -d \" | sed "s|$|+$BUILD_NUMBER|g")
export BASE_VERSION=$(npm pkg get version | tr -d \")

envsubst '$ARTIFACTORY_URL,$VERSION_WITH_BUILDNUMBER,$BASE_VERSION' <.cirrus/dogfood-template.json > dogfood.json
jfrog rt u dogfood.json sonarsource-public-builds/org/sonarsource/sonarlint/vscode/sonarlint-vscode/ \
      --url "${ARTIFACTORY_URL}" --access-token "${ARTIFACTORY_API_KEY}" --build-name "$CIRRUS_REPO_NAME" --build-number "$BUILD_NUMBER"
