#!/bin/bash

set -euo pipefail
# Fetch all commit history so that SonarQube has exact blame information
# for issue auto-assignment
# This command can fail with "fatal: --unshallow on a complete repository does not make sense"
# if there are not enough commits in the Git repository
# For this reason errors are ignored with "|| true"
git fetch --unshallow || true

# fetch references from github for PR analysis
if [ -n "${GITHUB_BASE_BRANCH}" ]; then
	git fetch origin "${GITHUB_BASE_BRANCH}"
fi

PROJECT_VERSION=$(npm pkg get version | tr -d \")
SONAR_PROJECT_KEY="org.sonarsource.sonarlint.vscode:sonarlint-vscode"
SONAR_ORGANIZATION="sonarsource"
SONAR_PROJECT_NAME="SonarLint for VSCode"


if [ "${GITHUB_BRANCH}" == "master" ] && [ "$PULL_REQUEST" == "false" ]; then
  echo '======= Analyze master branch'

  git fetch origin "${GITHUB_BRANCH}"

  # Analyze with SNAPSHOT version as long as SQ does not correctly handle
  # purge of release data

  npx sonar-scanner \
      -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
      -Dsonar.organization="$SONAR_ORGANIZATION" \
      -Dsonar.projectName="$SONAR_PROJECT_NAME" \
      -Dsonar.projectVersion="$PROJECT_VERSION" \
      -Dsonar.host.url="$SONARQUBE_NEXT_URL" \
      -Dsonar.token="$SONARQUBE_NEXT_TOKEN" \
      -Dsonar.analysis.buildNumber="$BUILD_NUMBER" \
      -Dsonar.analysis.pipeline="$CIRRUS_BUILD_ID" \
      -Dsonar.analysis.sha1="$GIT_SHA1"  \
      -Dsonar.analysis.repository="$GITHUB_REPO"

elif [[ "${GITHUB_BRANCH}" == "branch-"* ]] && [ "$PULL_REQUEST" == "false" ]; then
  # analyze maintenance branches as long-living branches

  # Fetch all commit history so that SonarQube has exact blame information
  # for issue auto-assignment
  # This command can fail with "fatal: --unshallow on a complete repository does not make sense"
  # if there are not enough commits in the Git repository
  # For this reason errors are ignored with "|| true"
  git fetch --unshallow || true

  git fetch origin "${GITHUB_BRANCH}"

  npx sonar-scanner \
      -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
      -Dsonar.organization="$SONAR_ORGANIZATION" \
      -Dsonar.projectName="$SONAR_PROJECT_NAME" \
      -Dsonar.host.url="$SONARQUBE_NEXT_URL" \
      -Dsonar.token="$SONARQUBE_NEXT_TOKEN" \
      -Dsonar.analysis.buildNumber="$BUILD_NUMBER" \
      -Dsonar.analysis.pipeline="$CIRRUS_BUILD_ID" \
      -Dsonar.analysis.sha1="$GIT_SHA1"  \
      -Dsonar.analysis.repository="$GITHUB_REPO" \
      -Dsonar.branch.name="$GITHUB_BRANCH"

elif [ "$PULL_REQUEST" != "false" ]; then
  echo '======= Analyze pull request'

  npx sonar-scanner \
      -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
      -Dsonar.organization="$SONAR_ORGANIZATION" \
      -Dsonar.projectName="$SONAR_PROJECT_NAME" \
      -Dsonar.host.url="$SONARQUBE_NEXT_URL" \
      -Dsonar.token="$SONARQUBE_NEXT_TOKEN" \
      -Dsonar.analysis.buildNumber="$BUILD_NUMBER" \
      -Dsonar.analysis.pipeline="$CIRRUS_BUILD_ID" \
      -Dsonar.analysis.sha1="$GIT_SHA1"  \
      -Dsonar.analysis.repository="$GITHUB_REPO" \
      -Dsonar.analysis.prNumber="$PULL_REQUEST"

elif [[ "$GITHUB_BRANCH" == "feature/long/"* ]] && [ "$PULL_REQUEST" == "false" ]; then
  echo '======= Analyze long lived feature branch'

  npx sonar-scanner \
      -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
      -Dsonar.organization="$SONAR_ORGANIZATION" \
      -Dsonar.projectName="$SONAR_PROJECT_NAME" \
      -Dsonar.host.url="$SONARQUBE_NEXT_URL" \
      -Dsonar.token="$SONARQUBE_NEXT_TOKEN" \
      -Dsonar.analysis.buildNumber="$BUILD_NUMBER" \
      -Dsonar.analysis.pipeline="$CIRRUS_BUILD_ID" \
      -Dsonar.analysis.sha1="$GIT_SHA1"  \
      -Dsonar.analysis.repository="$GITHUB_REPO" \
      -Dsonar.analysis.prNumber="$PULL_REQUEST" \
      -Dsonar.branch.name="$GITHUB_BRANCH"

else
  echo '======= No analysis'
fi
