env:
  CIRRUS_CLONE_DEPTH: "20"
  # Use bash (instead of sh on linux or cmd.exe on Windows)
  CIRRUS_SHELL: bash
  # burgr notification
  BURGR_URL: VAULT[development/kv/data/burgr data.url]
  BURGR_USERNAME: VAULT[development/kv/data/burgr data.cirrus_username]
  BURGR_PASSWORD: VAULT[development/kv/data/burgr data.cirrus_password]
  # repox
  ARTIFACTORY_URL: VAULT[development/kv/data/repox data.url]
  ARTIFACTORY_PRIVATE_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader
  ARTIFACTORY_PRIVATE_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-private-reader access_token]
  ARTIFACTORY_DEPLOY_USERNAME: vault-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer
  ARTIFACTORY_DEPLOY_PASSWORD: VAULT[development/artifactory/token/${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}-qa-deployer access_token]
  ARTIFACTORY_DEPLOY_REPO: sonarsource-public-qa

  ARTIFACTORY_PRIVATE_READER_USERNAME: $ARTIFACTORY_PRIVATE_USERNAME
  ARTIFACTORY_PRIVATE_READER_PASSWORD: $ARTIFACTORY_PRIVATE_PASSWORD
  GPG_SIGNING_KEY: VAULT[development/kv/data/sign data.key]
  GPG_SIGNING_PASSPHRASE: VAULT[development/kv/data/sign data.passphrase]

  SONAR_TOKEN: VAULT[development/kv/data/next data.token]
  SONAR_HOST_URL: VAULT[development/kv/data/next data.url]

auto_cancellation: $CIRRUS_BRANCH != 'master'

eks_container: &CONTAINER_DEFINITION
  dockerfile: .cirrus/Dockerfile
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
  region: eu-central-1
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  namespace: default

eks_xvfb_container: &XVFB_CONTAINER_DEFINITION
  dockerfile: .cirrus/XVFB_Dockerfile
  docker_arguments:
    CIRRUS_AWS_ACCOUNT: ${CIRRUS_AWS_ACCOUNT}
    JDK_VERSION: 11
  region: eu-central-1
  cluster_name: ${CIRRUS_CLUSTER_NAME}
  builder_role: cirrus-builder
  builder_image: docker-builder-v*
  builder_instance_type: t2.small
  builder_subnet_id: ${CIRRUS_AWS_SUBNET}
  namespace: default

ec2_instance: &WINVM_DEFINITION
  experimental: true
  image: base-windows-jdk17-v*
  platform: windows
  region: eu-central-1
  subnet_id: ${CIRRUS_AWS_SUBNET}
  type: t3.xlarge

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*")

skip_master_branch_and_allvsix_branch: &SKIP_MASTER_BRANCH_AND_ALLVSIX_BRANCH
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH != "master"  && ($CIRRUS_PR != "" && $CIRRUS_BRANCH !=~ ".*allvsix"))

only_master_or_allvsix_branch: &ONLY_MASTER_BUILD_OR_ALLVSIX_BRANCH
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || ($CIRRUS_PR != "" && $CIRRUS_BRANCH =~ ".*allvsix"))


only_if_base: &ONLY_IF
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == ""

only_if_with_nightly: &ONLY_IF_WITH_NIGHTLY
  only_if: ($CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_CRON == 'nightly-mend-scan') && $CIRRUS_TAG == ""

only_pr_and_maintained_branches: &ONLY_PR_AND_MAINTAINED_BRANCHES
  only_if: $CIRRUS_PR != "" || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BRANCH =~ "dogfood-on-.*"

only_main_branches: &ONLY_MAIN_BRANCHES
  only_if: $CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*"

node_modules_cache_template: &NODE_MODULES_CACHE_TEMPLATE
  node_modules_cache:
    folder: "node_modules"
    fingerprint_script:
      - node --version
      - cat package-lock.json
    populate_script: npm install

build_task:
  <<: *ONLY_SONARSOURCE_QA
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  <<: *NODE_MODULES_CACHE_TEMPLATE
  setup_script:
    - source cirrus-env BUILD # Generates a build number
    - echo $BUILD_NUMBER
    - export PACKAGE_VERSION=$(npm pkg get version | sed "s|-SNAPSHOT|+$BUILD_NUMBER|g")
    - echo PACKAGE_VERSION=${PACKAGE_VERSION}

#deploy_universal_vsix_task:
#  name: Deploy universal VSIX
#  alias: deploy_universal_vsix
#  depends_on: build
#  <<: *SKIP_MASTER_BRANCH_AND_ALLVSIX_BRANCH
#  eks_container:
#    <<: *CONTAINER_DEFINITION
#    cpu: 2
#    memory: 2G
#  <<: *NODE_MODULES_CACHE_TEMPLATE
#  deploy_script:
#    - source cirrus-env QA # Retrieve build number
#    - node_modules/.bin/gulp deploy
#
#deploy_all_vsix_files_task:
#  name: Deploy all VSIX files
#  alias: deploy_all_vsix_files
#  <<: *ONLY_MASTER_BUILD_OR_ALLVSIX_BRANCH
#  depends_on: build
#  eks_container:
#    <<: *CONTAINER_DEFINITION
#    cpu: 2
#    memory: 2G
#  <<: *NODE_MODULES_CACHE_TEMPLATE
#  deploy_all_script:
#    - source cirrus-env QA # Retrieve build number
#    - node_modules/.bin/gulp deploy-all

validate_task:
  # Run tests, SonarQube analysis
  depends_on: build
  eks_container:
    <<: *CONTAINER_DEFINITION
    cpu: 2
    memory: 2G
  <<: *NODE_MODULES_CACHE_TEMPLATE
  script:
    - echo "Validate"

test_windows_task:
#  name: Run tests on Windows
  depends_on: validate
  ec2_instance:
    <<: *WINVM_DEFINITION
  <<: *NODE_MODULES_CACHE_TEMPLATE
  script:
    - source cirrus-env QA
    - npm run compile
    - npm run prepare
    - npm run test-cov
  always:
    unit_tests_artifacts:
      path: '**/alltests.xml'
      format: junit

test_linux_task:
#  name: Run tests on Linux
  depends_on: validate
  eks_container:
    <<: *XVFB_CONTAINER_DEFINITION
    cpu: 4
    memory: 4G
  env:
    DISPLAY: ":10"
    SONARQUBE_NEXT_TOKEN: VAULT[development/kv/data/next data.token]
    SONARQUBE_NEXT_URL: VAULT[development/kv/data/next data.url]
  <<: *NODE_MODULES_CACHE_TEMPLATE
  start_virtual_screen_background_script:
    - xvfb_daemon_start
  script:
    - sleep 5
    - source cirrus-env QA
    - npm run compile
    - npm run prepare
    - npm run test-cov
  sonarqube_analysis_script: |
    node_modules/sonarqube-scanner/src/bin/sonar-scanner \
      -Dsonar.projectKey="org.sonarsource.sonarlint.vscode:sonarlint-vscode" \
      -Dsonar.organization="sonarsource" \
      -Dsonar.projectName="SonarLint for VSCode" \
      -Dsonar.host.url="$SONARQUBE_NEXT_URL" \
      -Dsonar.token="$SONARQUBE_NEXT_TOKEN" \
      -Dsonar.branch.name="$GITHUB_BRANCH" \
      -Dsonar.analysis.buildNumber="$BUILD_NUMBER" \
      -Dsonar.analysis.sha1="$GIT_SHA1"  \
      -Dsonar.analysis.repository="$GITHUB_REPO"

  always:
    unit_tests_artifacts:
      path: '**/alltests.xml'
      format: junit

mend_scan_task:
  depends_on:
    - test_linux
  <<: *ONLY_IF_WITH_NIGHTLY
  <<: *ONLY_MAIN_BRANCHES
  eks_container:
    <<: *CONTAINER_DEFINITION
#  <<: *MAVEN_CACHE_DEFINITION
  env:
    WS_APIKEY: VAULT[development/kv/data/mend data.apikey]
    WS_PRODUCTNAME: SonarLint/VSCode
    JDK_VERSION: "11"
  prepare_scripts:
    - export MEND_PROJECT_VERSION=${PACKAGE_VERSION}.replace('-SNAPSHOT', '')
  whitesource_script:
    - source cirrus-env QA # read build number
    - export PACKAGE_VERSION=$(npm pkg get version | sed "s|-SNAPSHOT|+$BUILD_NUMBER|g")

    # TODO: adapt for NPM
#    - mvn clean install -DskipTests
    - source ws_scan.sh
#  cleanup_before_cache_script: cleanup_maven_repository
  allow_failures: "true"
  always:
    ws_artifacts:
      path: "whitesource/**/*"

qa_task:
#  name: Run ITs
  depends_on: validate
  eks_container:
    <<: *XVFB_CONTAINER_DEFINITION
    cpu: 4
    memory: 4G
  <<: *NODE_MODULES_CACHE_TEMPLATE
  matrix:
    - env:
        QA_CATEGORY: oldest_supported
        VSCODE_VERSION: '1.73.0'
    - env:
        QA_CATEGORY: stable
        VSCODE_VERSION: 'stable'
    - env:
        QA_CATEGORY: insiders
        VSCODE_VERSION: 'insiders'
  env:
    DISPLAY: ":10"
    RECORD_FILENAME: "${CIRRUS_WORKING_DIR}/record_vscode_${QA_CATEGORY}.mp4"
  prepare_tests_script:
    - source cirrus-env QA
    - npm i
    - node_modules/.bin/gulp package
    - cd its
    - npm i
  start_screen_recording_background_script:
    - xvfb_daemon_start
    - sleep 10 # give xvfb some time to start
    - ffmpeg -f x11grab -video_size 1024x768 -i ${DISPLAY} -codec:v libx264 -r 12 -vf "drawtext=text='%{localtime\:%T} UTC':x=w-tw-10:y=5:fontcolor=black:fontsize=20" ${RECORD_FILENAME}
  test_script:
    - source cirrus-env QA
    - npm test
  stop_screen_recording_script:
    - pkill -SIGINT -f ffmpeg
    - sleep 5
    - xvfb_daemon_stop
  always:
    unit_tests_artifacts:
      path: '**/*tests.xml'
      format: junit
    test_recording_artifacts:
      path: ${RECORD_FILENAME}

dogfood_task:
  depends_on:
    - validate
    - qa
  script:
    - echo TODO - Implement it # TODO: implement this
