sudo: false

git:
  depth: false

language: node_js
node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"
    - "~/.sonar"

install:
  - npm install

script:
  - ./node_modules/.bin/gulp clean deploy && ./node_modules/.bin/gulp sonarqube

notifications:
  email: false
  webhooks:
    - secure: "PpiIE79N41Ow4+/MzKbbR5darevrklNqCviikioPgk+83BQ7aMRTbn5jibwXamy2PgNgTckG38BxPDCTbx3NrOycV3Of20LCeSFnNniXM0aL/tDrgB0PHs76TgdAyUEik8JPOwTEOf/0Y3z7LNBTOcyLaVEXu7HUQgqdXuOXkBjVxOlwLv9A87ivECHDqUZUZwPJwq1UweYz94Pv+33g189E5eqk//W4ENAeX5/IRCP3yKc28ERSReBUwG8yF0DevNrMTAW8NSHJMX10CrT9MbFei3TqwRhb2lrGD12+qTttKGwJDZx8cXteVz6SbLaHJd8FyDUV43sK2iMskJy2mcNoP+v4LLk5bFFrQYbeIp7wszbBjxmnvnoZnmQ+BrXzmj1p/UbThSgnoA3J/tVC1XImJuCTvfQ2O7LRWJLoTZl0ztpozNlbdKBzObugma2QkAZt/mkKmp9cofGggEP9f04qq6YFOWPZl1/McpH4fWCxAhOwbGvnJL/UjN5TvUgYu/Z8sQnI6tALjTeYZewT+EZJab2N1U8vwX+GOs8lp2tcJwIC3Nr5MnFiAB3hmAzhrXJzn2VTJ1hYuLZjOoGxovhYWlVm2eulkg7+VNDZV7+46jn/0gh2hw76qMIyaVqtb2ul2tMG8lrBPj8F7ciz/nLhToQP6iV/j6JYxJHQErA="
  on_start: always
