name: test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  check-credentials:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    name: Check release credentials are valid
    env:
      ARTIFACTORY_URL: https://repox.jfrog.io/artifactory
    steps:
      - name: Checkout custom actions
        uses: actions/checkout@v3
        with:
          clean: false
      - name: Get vault secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@dc8fe04652687f7278f3ecd27905967836bab0eb # tag=2.7.4-1
        with:
          secrets: |
            development/artifactory/token/{REPO_OWNER_NAME_DASH}-private-reader access_token | ARTIFACTORY_ACCESS_TOKEN;
            development/kv/data/visualstudio VSCE_TOKEN | VISUALSTUDIO_PAT;
            development/team/sonarlint/kv/data/openvsx token | OPENVSX_TOKEN;
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          OPENVSX: ${{ secrets.OPENVSX_TOKEN }}
